-- ============================================================
-- Docbase metadata tables from SQL Server converted to PostgreSQL
-- ============================================================

CREATE TABLE IF NOT EXISTS xoaf_form_s (
  r_object_id          CHAR(16) NOT NULL,
  i_partition          INTEGER,
  payment_terms        VARCHAR(256) NOT NULL,
  total_comm_above_purchase DOUBLE PRECISION NOT NULL,
  special_comments     VARCHAR(4000) NOT NULL,
  file_ref_no          VARCHAR(256) NOT NULL,
  justification        VARCHAR(4000) NOT NULL,
  eval_fcg_approval_date TIMESTAMP WITH TIME ZONE NOT NULL,
  checker_intender     VARCHAR(255) NOT NULL,
  mom_of_negotiations  VARCHAR(256) NOT NULL,
  ld_clause            VARCHAR(64) NOT NULL,
  checker_intender_app_date TIMESTAMP WITH TIME ZONE NOT NULL,
  query_raised         SMALLINT NOT NULL,
  eval_fcg             VARCHAR(255) NOT NULL,
  status               VARCHAR(64) NOT NULL,
  ras_details          VARCHAR(1024) NOT NULL,
  regulatory_approval  VARCHAR(64) NOT NULL,
  eval_intender        VARCHAR(255) NOT NULL,
  offer_text           VARCHAR(4000) NOT NULL,
  offer_received_from  INTEGER NOT NULL,
  checker_fcg          VARCHAR(255) NOT NULL,
  soa_value            VARCHAR(250) NOT NULL,
  eval_cc_approval_date TIMESTAMP WITH TIME ZONE NOT NULL,
  dcp_required         VARCHAR(4000) NOT NULL,
  offer_validity       TIMESTAMP WITH TIME ZONE NOT NULL,
  budget               VARCHAR(64) NOT NULL,
  company_code         VARCHAR(256) NOT NULL,
  ld_clause_text       VARCHAR(4000) NOT NULL,
  scope                VARCHAR(4000) NOT NULL,
  pbg                  VARCHAR(64) NOT NULL,
  costbenchmarking_remark VARCHAR(4000) NOT NULL,
  process_type         VARCHAR(255) NOT NULL,
  checker_cc_approval_date TIMESTAMP WITH TIME ZONE,
  purpose              VARCHAR(4000),
  negotiation_comments VARCHAR(4000),
  approval_pending_with VARCHAR(256),
  approval_level       INTEGER,
  area                 VARCHAR(64),
  final_approver_app_date TIMESTAMP WITH TIME ZONE,
  final_approver       VARCHAR(255),
  dcp_agreed           VARCHAR(4000),
  eval_cc              VARCHAR(255),
  payment_text         VARCHAR(4000),
  checker_fcg_approval_date TIMESTAMP WITH TIME ZONE,
  capex_fy             VARCHAR(256),
  capex_details        VARCHAR(4000),
  checker_cc           VARCHAR(256),
  bidding_details      VARCHAR(4000),
  eoaf_subject         VARCHAR(125),
  total_comm_incl_contigency DOUBLE PRECISION,
  soa_clause           VARCHAR(256),
  eval_intender_approval_date TIMESTAMP WITH TIME ZONE,
  oaf_num              VARCHAR(256),
  eoaf_type            VARCHAR(64),
  request_for_bids_sent_to INTEGER,
  approver1            VARCHAR(255),
  final_approver_grade VARCHAR(64),
  approver1_grade      VARCHAR(64),
  checker_cc_grade     VARCHAR(64),
  department           VARCHAR(255),
  total_negotiated_savings_pe DOUBLE PRECISION,
  checker_fcg_grade    VARCHAR(64),
  approver1_approval_date TIMESTAMP WITH TIME ZONE,
  checker_intender_grade VARCHAR(64),
  initiation_date      TIMESTAMP WITH TIME ZONE,
  memo_year            VARCHAR(255),
  total_negotiated_savings_rs DOUBLE PRECISION,
  cost_center_code     VARCHAR(255),
  department_code      VARCHAR(255),
  eval_cc_position     VARCHAR(255),
  checker_intender_position VARCHAR(64),
  checker_fcg_position VARCHAR(64),
  eval_intender_grade  VARCHAR(64),
  final_approver_position VARCHAR(64),
  checker_cc_position  VARCHAR(64),
  eval_fcg_grade       VARCHAR(64),
  approver_1_position  VARCHAR(64),
  eval_fcg_position    VARCHAR(64),
  eval_intender_position VARCHAR(64),
  eval_cc_grade        VARCHAR(64),
  payment_period       VARCHAR(64),
  earlier_approval_type VARCHAR(256),
  oaf_no_ammended      VARCHAR(256),
  is_amd               SMALLINT,
  budget_details       VARCHAR(4000),
  revised_delivery_schedule VARCHAR(4000),
  category             VARCHAR(255),
  detail_scope_of_work SMALLINT,
  job_duration         VARCHAR(64),
  module               VARCHAR(255),
  estimated_value      VARCHAR(64),
  cost_estimate        DOUBLE PRECISION,
  safety_concurrence   VARCHAR(64),
  suggested_vendor     VARCHAR(2000),
  budgetory_offer      SMALLINT,
  tendering            VARCHAR(64),
  job_type             VARCHAR(64),
  justifi_emrg_pr      VARCHAR(4000),
  safety               SMALLINT,
  service_additional_details VARCHAR(4000),
  nature               VARCHAR(255),
  service_backup_for_estimati VARCHAR(255),
  material_additional_details VARCHAR(4000),
  amount_mode          VARCHAR(64),
  budget_additional_details VARCHAR(4000),
  material_backup_for_estimat VARCHAR(255),
  renewal_period_to    TIMESTAMP WITH TIME ZONE,
  renewal_period_from  TIMESTAMP WITH TIME ZONE,
  negotiation_saving_fcg VARCHAR(255),
  po_manager           VARCHAR(255),
  negotiated_savings   VARCHAR(255),
  renewal              VARCHAR(64),
  type_of_request      VARCHAR(255),
  date_of_receipt_of_tech_eva TIMESTAMP WITH TIME ZONE,
  type_of_negotiation  VARCHAR(64),
  qr_oa_technical      VARCHAR(4000),
  order_award_criteria VARCHAR(1000),
  qr_oa_commercial     VARCHAR(4000),
  period_of_contract   VARCHAR(4000),
  technical_bid_opening_date TIMESTAMP WITH TIME ZONE,
  eoi_publishing_date  TIMESTAMP WITH TIME ZONE,
  type_of_bidding      VARCHAR(200),
  eoi_publishing_media VARCHAR(4000),
  proposal_pertaining_to VARCHAR(255),
  type_of_proposal     VARCHAR(200),
  date_of_price_bid_opening TIMESTAMP WITH TIME ZONE,
  purchasing_group     VARCHAR(255),
  bid_submission_date  TIMESTAMP WITH TIME ZONE,
  perform_report_of_prop_bidd VARCHAR(4000),
  safety_evaluation_date TIMESTAMP WITH TIME ZONE,
  date_of_reverse_auction TIMESTAMP WITH TIME ZONE,
  date_of_negotiation  TIMESTAMP WITH TIME ZONE,
  safety_bids_date     TIMESTAMP WITH TIME ZONE,
  date_of_fwd_tech_bid_to_use TIMESTAMP WITH TIME ZONE,
  subsidiary           VARCHAR(255),
  clusters             VARCHAR(255),
  quantity_justification VARCHAR(4000),
  budget_chargeability INTEGER,
  budget_chargeability_1 VARCHAR(64),
  vendor_type          VARCHAR(256),
  expected_cost        INTEGER,
  recommendation_checkbox SMALLINT,
  scope_negotiated     VARCHAR(255),
  payment_term         VARCHAR(1024),
  ver                  VARCHAR(64),
  ld_text              VARCHAR(1024),
  pbg_text             VARCHAR(1024),
  ariba_no             VARCHAR(512),
  date_of_completion_of_comme TIMESTAMP WITH TIME ZONE,
  financial_turnover_for_the_ VARCHAR(500),
  manual_negotiation_conducte VARCHAR(64),
  nit_initiation_date   TIMESTAMP WITH TIME ZONE,
  past_association_with_tata_ VARCHAR(1024),
  nit_approval_date      TIMESTAMP WITH TIME ZONE,
  special_conditons_of_contra VARCHAR(1024),
  manual_date_of_negotiation TIMESTAMP WITH TIME ZONE,
  delivery_terms         VARCHAR(4000),
  award_others           VARCHAR(2048),
  receipt_of_customer_share VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_xoaf_form_s_r_object_id ON xoaf_form_s(r_object_id);
CREATE INDEX IF NOT EXISTS idx_xoaf_form_s_i_partition ON xoaf_form_s(i_partition);
CREATE INDEX IF NOT EXISTS idx_xoaf_form_s_form_id ON xoaf_form_s(file_ref_no);
CREATE INDEX IF NOT EXISTS idx_xoaf_form_s_status ON xoaf_form_s(status);

CREATE TABLE IF NOT EXISTS xoaf_form_r (
  r_object_id CHAR(16) NOT NULL,
  i_position SMALLINT,
  i_partition INTEGER,
  pr_number VARCHAR(11),
  md_email_cc_users VARCHAR(250)
);

CREATE INDEX IF NOT EXISTS idx_xoaf_form_r_r_object_id ON xoaf_form_r(r_object_id);
CREATE INDEX IF NOT EXISTS idx_xoaf_form_r_i_partition ON xoaf_form_r(i_partition);
CREATE INDEX IF NOT EXISTS idx_xoaf_form_r_pr_number ON xoaf_form_r(pr_number);

CREATE TABLE IF NOT EXISTS xoaf_enclosure_s (
  r_object_id CHAR(16) NOT NULL,
  i_partition INTEGER,
  form_id VARCHAR(64) NOT NULL,
  "type" VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_xoaf_enclosure_s_r_object_id ON xoaf_enclosure_s(r_object_id);
CREATE INDEX IF NOT EXISTS idx_xoaf_enclosure_s_form_id ON xoaf_enclosure_s(form_id);
CREATE INDEX IF NOT EXISTS idx_xoaf_enclosure_s_type ON xoaf_enclosure_s("type");
