

CREATE TABLE IF NOT EXISTS dm_sysobject_s (
    r_object_id             VARCHAR(16)     NOT NULL PRIMARY KEY,
    owner_name              VARCHAR(255)    NOT NULL DEFAULT '',
    r_creation_date         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    r_modify_date           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    object_name             VARCHAR(255)    NOT NULL DEFAULT '',
    r_object_type           VARCHAR(32)     NOT NULL DEFAULT '',
    title                   VARCHAR(400)    NOT NULL DEFAULT '',
    subject                 VARCHAR(192)    NOT NULL DEFAULT '',
    a_application_type      VARCHAR(32)     NOT NULL DEFAULT '',
    a_status                VARCHAR(16)     NOT NULL DEFAULT '',
    r_modifier              VARCHAR(255)    NOT NULL DEFAULT '',
    r_access_date           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    a_is_hidden             SMALLINT        NOT NULL DEFAULT 0,
    i_is_deleted            SMALLINT        NOT NULL DEFAULT 0,
    a_retention_date        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    a_archive               SMALLINT        NOT NULL DEFAULT 0,
    a_compound_architecture VARCHAR(16)     NOT NULL DEFAULT '',
    a_link_resolved         SMALLINT        NOT NULL DEFAULT 0,
    i_reference_cnt         INTEGER         NOT NULL DEFAULT 0,
    i_has_folder            SMALLINT        NOT NULL DEFAULT 0,
    r_link_cnt              INTEGER         NOT NULL DEFAULT 0,
    r_link_high_cnt         INTEGER         NOT NULL DEFAULT 0,
    r_assembled_from_id     VARCHAR(16)     NOT NULL DEFAULT '',
    r_frzn_assembly_cnt     INTEGER         NOT NULL DEFAULT 0,
    r_has_frzn_assembly     SMALLINT        NOT NULL DEFAULT 0,
    resolution_label        VARCHAR(32)     NOT NULL DEFAULT '',
    r_is_virtual_doc        INTEGER         NOT NULL DEFAULT 0,
    i_contents_id           VARCHAR(16)     NOT NULL DEFAULT '',
    a_content_type          VARCHAR(32)     NOT NULL DEFAULT '',
    r_page_cnt              INTEGER         NOT NULL DEFAULT 0,
    r_content_size          INTEGER         NOT NULL DEFAULT 0,
    a_full_text             SMALLINT        NOT NULL DEFAULT 0,
    a_storage_type          VARCHAR(64)     NOT NULL DEFAULT '',
    i_cabinet_id            VARCHAR(16)     NOT NULL DEFAULT '',
    owner_permit            INTEGER         NOT NULL DEFAULT 0,
    group_name              VARCHAR(255)    NOT NULL DEFAULT '',
    group_permit            INTEGER         NOT NULL DEFAULT 0,
    world_permit            INTEGER         NOT NULL DEFAULT 0,
    i_antecedent_id         VARCHAR(16)     NOT NULL DEFAULT '',
    i_chronicle_id          VARCHAR(16)     NOT NULL DEFAULT '',
    i_latest_flag           SMALLINT        NOT NULL DEFAULT 1,
    r_lock_owner            VARCHAR(255)    NOT NULL DEFAULT '',
    r_lock_date             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    r_lock_machine          VARCHAR(80)     NOT NULL DEFAULT '',
    log_entry               VARCHAR(120)    NOT NULL DEFAULT '',
    i_branch_cnt            INTEGER         NOT NULL DEFAULT 0,
    i_direct_dsc            SMALLINT        NOT NULL DEFAULT 0,
    r_immutable_flag        SMALLINT        NOT NULL DEFAULT 0,
    r_frozen_flag           SMALLINT        NOT NULL DEFAULT 0,
    r_has_events            SMALLINT        NOT NULL DEFAULT 0,
    acl_domain              VARCHAR(255)    NOT NULL DEFAULT '',
    acl_name                VARCHAR(32)     NOT NULL DEFAULT '',
    a_special_app           VARCHAR(32)     NOT NULL DEFAULT '',
    i_is_reference          SMALLINT        NOT NULL DEFAULT 0,
    r_creator_name          VARCHAR(255)    NOT NULL DEFAULT '',
    r_is_public             SMALLINT        NOT NULL DEFAULT 0,
    r_policy_id             VARCHAR(16)     NOT NULL DEFAULT '',
    r_resume_state          INTEGER         NOT NULL DEFAULT 0,
    r_current_state         INTEGER         NOT NULL DEFAULT 0,
    r_alias_set_id          VARCHAR(16)     NOT NULL DEFAULT '',
    a_category              VARCHAR(64)     NOT NULL DEFAULT '',
    language_code           VARCHAR(5)      NOT NULL DEFAULT '',
    a_is_template           SMALLINT        NOT NULL DEFAULT 0,
    a_controlling_app       VARCHAR(32)     NOT NULL DEFAULT '',
    r_full_content_size     FLOAT           NOT NULL DEFAULT 0,
    a_is_signed             SMALLINT        NOT NULL DEFAULT 0,
    a_last_review_date      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    i_retain_until          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    i_partition             INTEGER                  DEFAULT 0,
    i_is_replica            SMALLINT        NOT NULL DEFAULT 0,
    i_vstamp                INTEGER         NOT NULL DEFAULT 0,
    i_property_bag          VARCHAR(1024)            DEFAULT NULL
);

-- Indexes for Table A filter columns on dm_sysobject_s
CREATE INDEX IF NOT EXISTS idx_dm_sysobject_r_creation_date ON dm_sysobject_s (r_creation_date);
CREATE INDEX IF NOT EXISTS idx_dm_sysobject_owner_name      ON dm_sysobject_s (owner_name);
